const FACILITY_STATUS = {
  AVAILABLE: "AVAILABLE",
  MAINTENANCE: "MAINTENANCE",
  INACTIVE: "INACTIVE",
};

const FACILITY_STATUS_VALUES = Object.values(FACILITY_STATUS);

export { FACILITY_STATUS, FACILITY_STATUS_VALUES };
